### ISSUE TITLE
scw

### ISSUE THREAD

**Issue by kjkui** [Galaxy1036/scCredentialsDecrypt#1]
Hello. How decrypt scw

**Comment by Galaxy1036** [comment]
SCW files are not encrypted at all, actually there are no open sourced tools to deal with them

**Comment by kjkui** [comment]
they can be converted to a format that is known, for example .dae?

**Comment by kjkui** [comment]
mtllib male_gunslingerhead1.mtl
o male_gunslingerhead1_GaLaXy1036

**Comment by Galaxy1036** [comment]
Ofc you can extract models and save them as .dae but actually nobody open-sourced a tool to do it

**Comment by kjkui** [comment]
so you didn't make a script to convert scw to dae?

**Comment by Galaxy1036** [comment]
I made a script but actually it's not completely finished so i keep it private

**Comment by kjkui** [comment]
will it ever be in the public domain?

**Comment by Galaxy1036** [comment]
If i finish it ofc

**Comment by kjkui** [comment]
does the SCW format store animation?

**Comment by Galaxy1036** [comment]
As far as i know yes

**Comment by kjkui** [comment]
and when your script is finished, will it save the animation or just the model?

**Comment by kjkui** [comment]
Can I communicate with you by e-mail?

**Comment by Galaxy1036** [comment]
My script will contains every features if i finish it (texture, animations, camera etc...)

**Comment by Galaxy1036** [comment]
Discord would be better i think (add me at @GaLaXy1036#1601)

**Comment by kjkui** [comment]
discord?

**Comment by Galaxy1036** [comment]
Yeah

**Comment by kjkui** [comment]
i can't

**Comment by kjkui** [comment]
you try to add me (#8989-Полина)

**Comment by alickmail** [comment]
Could you kindly add me too? Thanks! (AlickWong#1824)

**Comment by Galaxy1036** [comment]
Sure !

**Comment by Legenda242019** [comment]
hey guy can you add me in discord

**Comment by Legenda242019** [comment]
> 
> 
> SCW files are not encrypted at all, actually there are no open sourced tools to deal with them

hey guy can you add me on discord

**Comment by Yuself** [comment]
Can you add me, too?
Yuyouself#9145
thanks!
